i2c:
  - id: bus_a
    sda: ${i2c_sda}
    scl: ${i2c_scl}
    scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    i2c_id: bus_a
