i2c:
  - id: bus_a
    sda: ${bme280_sda}
    scl: ${bme280_scl}
    scan: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: ${device_friendly_name} Temperature
      id: bme280_temperature
    pressure:
      name: ${device_friendly_name} Pressure
      id: bme280_pressure
    humidity:
      name: ${device_friendly_name} Humidity
      id: bme280_humidity
    i2c_id: bus_a
    address: 0x76
