esphome:
  name: esp32-s3
  friendly_name: ESP32 S3
  min_version: 2025.10.0
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True

api:

logger:

ota:
  - platform: esphome
    id: ota_esphome

time:
  - platform: homeassistant
    id: homeassistant_time 

web_server:
  local: true

