esphome:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy
  min_version: 2025.5.0
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:

api:

logger:

ota:
  - platform: esphome
    id: ota_esphome

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

time:
  - platform: homeassistant
    id: homeassistant_time 

web_server:
  local: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: ${gpio_pin}
    num_leds: 1
    chipset: ws2812
    name: "Status Light" 
    id: ${device_id}_light
