esphome:
  name: esp32-multi-sensor
  friendly_name: ESP32 Multi Sensor
  min_version: 2025.6.0
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:

api:

logger:

ota:
  - platform: esphome
    id: ota_esphome

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: false

time:
  - platform: homeassistant
    id: homeassistant_time 

web_server:
  local: true
