# LD2410C Config
ld2410:

uart:
  tx_pin: ${ld24_tx}
  rx_pin: ${ld24_rx}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: Out pin presence status 
