# LD2410C Config
ld2410:

uart:
  tx_pin: ${ld24_tx}
  rx_pin: ${ld24_rx}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: ld24_presence
    has_moving_target:
      name: Moving Target
      id: ld24_moving_target
    has_still_target:
      name: Still Target
      id: ld24_still_target
    out_pin_presence_status:
      name: Out pin presence status
      id: ld24_out_pin_presence_status

sensor:
  - platform: ld2410
    light:
      name: LD24 Light
      id: ld24_light
    moving_distance:
      name: Moving Distance
      id: ld24_moving_distance
    still_distance:
      name: Still Distance
      id: ld24_still_distance
    moving_energy:
      name: Move Energy
      id: ld24_move_energy
    still_energy:
      name: Still Energy
      id: ld24_still_energy
    detection_distance:
      name: Detection Distance
      id: ld24_detection_distance
    g0:
      move_energy:
        name: G0 move energy
        id: ld24_g0_move_energy
      still_energy:
        name: G0 still energy
        id: ld24_g0_still_energy
    g1:
      move_energy:
        name: G1 move energy
        id: ld24_g1_move_energy
      still_energy:
        name: G1 still energy
        id: ld24_g1_still_energy
    g2:
      move_energy:
        name: G2 move energy
        id: ld24_g2_move_energy
      still_energy:
        name: G2 still energy
        id: ld24_g2_still_energy
    g3:
      move_energy:
        name: G3 move energy
        id: ld24_g3_move_energy
      still_energy:
        name: G3 still energy
        id: ld24_g3_still_energy
    g4:
      move_energy:
        name: G4 move energy
        id: ld24_g4_move_energy
      still_energy:
        name: G4 still energy
        id: ld24_g4_still_energy
    g5:
      move_energy:
        name: G5 move energy
        id: ld24_g5_move_energy
      still_energy:
        name: G5 still energy
        id: ld24_g5_still_energy
    g6:
      move_energy:
        name: G6 move energy
        id: ld24_g6_move_energy
      still_energy:
        name: G6 still energy
        id: ld24_g6_still_energy
    g7:
      move_energy:
        name: G7 move energy
        id: ld24_g7_move_energy
      still_energy:
        name: G7 still energy
        id: ld24_g7_still_energy
    g8:
      move_energy:
        name: G8 move energy
        id: ld24_g8_move_energy
      still_energy:
        name: G8 still energy
        id: ld24_g8_still_energy

switch:
  - platform: ld2410
    engineering_mode:
      name: Engineering mode
      id: ld24_engineering_mode
    bluetooth:
      name: Control bluetooth
      id: ld24_control_bluetooth

number:
  - platform: ld2410
    timeout:
      name: Timeout
      id: ld24_timeout
    light_threshold:
      name: Light threshold
      id: ld24_light_threshold
    max_move_distance_gate:
      name: Max move distance gate
      id: ld24_max_move_distance_gate
    max_still_distance_gate:
      name: Max still distance gate
      id: ld24_max_still_distance_gate
    g0:
      move_threshold:
        name: G0 move threshold
        id: ld24_g0_move_threshold
      still_threshold:
        name: G0 still threshold
        id: ld24_g0_still_threshold
    g1:
      move_threshold:
        name: G1 move threshold
        id: ld24_g1_move_threshold
      still_threshold:
        name: G1 still threshold
        id: ld24_g1_still_threshold
    g2:
      move_threshold:
        name: G2 move threshold
        id: ld24_g2_move_threshold
      still_threshold:
        name: G2 still threshold
        id: ld24_g2_still_threshold
    g3:
      move_threshold:
        name: G3 move threshold
        id: ld24_g3_move_threshold
      still_threshold:
        name: G3 still threshold
        id: ld24_g3_still_threshold
    g4:
      move_threshold:
        name: G4 move threshold
        id: ld24_move_threshold
      still_threshold:
        name: G4 still threshold
        id: ld24_g4_still_threshold
    g5:
      move_threshold:
        name: G5 move threshold
        id: ld24_g5_move_threshold
      still_threshold:
        name: G5 still threshold
        id: ld24_g5_still_threshold
    g6:
      move_threshold:
        name: G6 move threshold
        id: ld24_g6_move_threshold
      still_threshold:
        name: G6 still threshold
        id: ld24_g6_still_threshold
    g7:
      move_threshold:
        name: G7 move threshold
        id: ld24_g7_move_threshold
      still_threshold:
        name: G7 still threshold
        id: ld24_g7_still_threshold
    g8:
      move_threshold:
        name: G8 move threshold
        id: ld24_g8_move_threshold
      still_threshold:
        name: G8 still threshold
        id: ld24_g8_still_threshold

button:
  - platform: ld2410
    factory_reset:
      name: LD2410 Factory reset
      id: ld24_factory_reset
    restart:
      name: LD2410 Restart
      id: ld24_restart
    query_params:
      name: LD2410 Query params
      id: ld24_query_param

text_sensor:
  - platform: ld2410
    version:
      name: LD2410 Firmware version
      id: ld24_firmware_version
    mac_address:
      name: LD2410 MAC address
      id: ld24_mac_address

select:
  - platform: ld2410
    distance_resolution:
      name: LD2410 Distance resolution
      id: ld24_distance_resolution
    baud_rate:
      name: LD2410 Baud rate
      id: ld24_baud_rate
    light_function:
      name: LD2410 Light function
      id: ld24_light_function
    out_pin_level:
      name: LD2410 Out pin level
      id: ld24_out_pin_level

