################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  - platform: status
    name: ${device_friendly_name} Status
    id: ${device_id}_status
    icon: mdi:check-circle

################################################################################
# Text Sensors
################################################################################
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_friendly_name} IP Address
      id: ip_address
      icon: mdi:ip-network
    ssid:
      name: ${device_friendly_name} SSID
      id: connected_ssid
      icon: mdi:wifi
    mac_address:
      name: ${device_friendly_name} MAC Address
      id: mac_address
      icon: mdi:router-wireless
  - platform: version
    name: ${device_friendly_name} ESPHome Version
    hide_timestamp: true
    icon: mdi:package-variant-closed
    id: esphome_version
  - platform: uptime
    name: ${device_friendly_name} Uptime
    id: ${device_id}_uptime
    format:
      separator: " "
      days: "D"    

sensor:
  - platform: template
    id: esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 60s


