i2c:
  sda: ${vl53l0x_sda}
  scl: ${vl53l0x_scl}

sensor:
  - platform: vl53l0x
    name: ${vl53l0x_name}
    id: ${vl53l0x_id}
    address: ${vl53l0x_address}
    timeout: 60s
    update_interval: 300s
    unit_of_measurement: "m"
    filters:
      - filter_out: nan
      - median:
          window_size: 3
          send_first_at: 1
    accuracy_decimals: 2
