i2c:
  sda: ${vl53l0x_sda}
  scl: ${vl53l0x_scl}

sensor:
  - platform: vl53l0x
    name: ${vl53l0x_name}
    id: "vl53l0x_range"
    address: ${vl53l0x_address}
    timeout: 60s
    update_interval: 12h
    filters:
      - lambda: return (${sensor_height}-x/${sensor_height}-0.1)*100;
    unit_of_measurement: "%"

  - platform: vl53l0x
    name: "${vl53l0x_name} Meters"
    id: "vl53l0x_range_meters"
    address: ${vl53l0x_address}
    timeout: 60s
    update_interval: 12h
    unit_of_measurement: "m"
    filters:
      - filter_out: nan
      - median:
          window_size: 3
          send_first_at: 1
    accuracy_decimals: 2
