substitutions:
  device_name: water-softener
  device_friendly_name: Water Softener
  device_id: water_softener
  device_sampling_time: 30s
  led_gpio: GPIO48
  num_leds: 1
  rgb_order: GRB
  vl53l0x_sda: GPIO16
  vl53l0x_scl: GPIO17
  vl53l0x_address: 0x29
  vl53l0x_name: Level
  ## The height of the sensor from floor in meters
  sensor_height: 0.88

packages:
  esp32: github://schettada/esphome/esp32-s3.yaml
  lights: github://schettada/esphome/lights.yaml
  vl53l0x: github://schettada/esphome/vl53l0x.yaml
  ble_proxy: github://schettada/esphome/ble-proxy.yaml

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: "hh0HBObiHIIXVKpAsnzFG9amwXeWrPyxx3HQ6JPG6N0="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True
